### ISSUE TITLE
has no method 'info'

### ISSUE THREAD

**Issue by bgobi1991** [Orion98MC/node_rrd#10]
D:\Angular Example\rrdtool\main.js:231
            rrd.info(filename, function (info) {
                ^
TypeError: Object #<Object> has no method 'info'
    at Server.<anonymous> (D:\Angular Example\rrdtool\main.js:231:17)
    at Server.emit (events.js:98:17)
    at HTTPParser.parser.onIncoming (http.js:2113:12)
    at HTTPParser.parserOnHeadersComplete [as onHeadersComplete] (http.js:122:23)
    at Socket.socket.ondata (http.js:1971:22)
    at TCP.onread (net.js:528:27)

**Comment by Orion98MC** [comment]
I guess you are asking me to solve your issue but:

1 - You don't give me enough information to do so
2 - You lack courtesy. I believe a "Hi" or a "Hello" would be a good start

Good day sir, miss, whatever...

**Comment by bgobi1991** [comment]
Hi Thierry Passeron,

Sorry for this, i included node rrd module when i call this method through this error,

TypeError: Object # has no method 'info'
at Server. (D:\Angular Example\rrdtool\main.js:231:17)
at Server.emit (events.js:98:17)
at HTTPParser.parser.onIncoming (http.js:2113:12)
at HTTPParser.parserOnHeadersComplete as onHeadersComplete
at Socket.socket.ondata (http.js:1971:22)
at TCP.onread (net.js:528:27)
