### ISSUE TITLE
npm install failure

### ISSUE THREAD

**Issue by wiseflat** [Orion98MC/node_rrd#12]
Hi, 
I have a problem.
I read the others issues and the installation procedure
node_gyp, build-essentials and librrd-dev are installed on my system.
I tried many times, same error...

Could you tell me why ?
Cheers man

```
pi@srv /tmp/node_rrd $ sudo npm install -g .
|
> rrd@0.0.5 install /usr/local/lib/node_modules/rrd
> node-gyp rebuild

gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/0.12.1"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/local/lib/node_modules/rrd/.node-gyp"
child_process: customFds option is deprecated, use stdio instead.
make: Entering directory '/usr/local/lib/node_modules/rrd/build'
  CXX(target) Release/obj.target/rrd_bindings/src/node_rrd_create.o
In file included from ../src/node_rrd_create.cc:27:0:
../src/node_rrd.h:56:5: error: ‘NanCallback’ does not name a type
../src/node_rrd.h: In destructor ‘node_rrd::AsyncInfos::~AsyncInfos()’:
../src/node_rrd.h:58:28: error: ‘callback’ was not declared in this scope
../src/node_rrd_create.cc: In function ‘Nan::NAN_METHOD_RETURN_TYPE node_rrd::create(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/node_rrd_create.cc:54:14: error: ‘NanScope’ was not declared in this scope
../src/node_rrd_create.cc:56:5: error: ‘args’ was not declared in this scope
../src/node_rrd_create.cc:56:5: error: ‘NanThrowTypeError’ was not declared in this scope
../src/node_rrd_create.cc:56:5: error: return-statement with a value, in function returning 'void' [-fpermissive]
../src/node_rrd_create.cc:59:5: error: declaration of ‘node_rrd::{anonymous}::Infos* info’ shadows a parameter
../src/node_rrd_create.cc:62:5: error: ‘args’ was not declared in this scope
../src/node_rrd_create.cc:74:5: error: ‘class node_rrd::{anonymous}::Infos’ has no member named ‘callback’
../src/node_rrd_create.cc:74:5: error: expected type-specifier before ‘NanCallback’
../src/node_rrd_create.cc:74:5: error: expected ‘;’ before ‘NanCallback’
../src/node_rrd_create.cc:78:24: error: ‘NanReturnUndefined’ was not declared in this scope
../src/node_rrd_create.cc: In function ‘void node_rrd::async_after(uv_work_t*)’:
../src/node_rrd_create.cc:94:14: error: ‘NanScope’ was not declared in this scope
../src/node_rrd_create.cc:98:37: error: ‘NanNull’ was not declared in this scope
../src/node_rrd_create.cc:99:36: error: ‘NanNew’ was not declared in this scope
../src/node_rrd_create.cc:99:49: error: expected primary-expression before ‘>’ token
../src/node_rrd_create.cc:100:11: error: ‘class node_rrd::{anonymous}::Infos’ has no member named ‘callback’
rrd_bindings.target.mk:88: recipe for target 'Release/obj.target/rrd_bindings/src/node_rrd_create.o' failed
make: *** [Release/obj.target/rrd_bindings/src/node_rrd_create.o] Error 1
make: Leaving directory '/usr/local/lib/node_modules/rrd/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1067:12)
gyp ERR! System Linux 4.1.6+
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/rrd
gyp ERR! node -v v0.12.1
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok
npm ERR! Linux 4.1.6+
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "."
npm ERR! node v0.12.1
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE

npm ERR! rrd@0.0.5 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the rrd@0.0.5 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the rrd package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls rrd
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /tmp/node_rrd/npm-debug.log
```

**Comment by djkeeg** [comment]
Refer to this closed Issue:

https://github.com/Orion98MC/node_rrd/issues/11
