### ISSUE TITLE
Pb with cflags_cc

### ISSUE THREAD

**Issue by wiseflat** [Orion98MC/node_rrd#16]
I installed your project on my raspberry pi jessie and I cannot install it..

```
/tmp/node_rrd $ sudo npm -g install
\
> rrd@0.0.5 install /usr/local/lib/node_modules/rrd
> node-gyp rebuild

gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/0.12.6"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/local/lib/node_modules/rrd/.node-gyp"
make: Entering directory '/usr/local/lib/node_modules/rrd/build'
  CXX(target) Release/obj.target/rrd_bindings/src/node_rrd_create.o
cc1plus: error: unrecognized command line option ‘-std=c++11’
rrd_bindings.target.mk:92: recipe for target 'Release/obj.target/rrd_bindings/src/node_rrd_create.o' failed
make: *** [Release/obj.target/rrd_bindings/src/node_rrd_create.o] Error 1
make: Leaving directory '/usr/local/lib/node_modules/rrd/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Linux 4.1.7-v7+
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/rrd
gyp ERR! node -v v0.12.6
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok
npm ERR! Linux 4.1.7-v7+
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "-g" "install"
npm ERR! node v0.12.6
npm ERR! npm  v2.11.2
npm ERR! code ELIFECYCLE

npm ERR! rrd@0.0.5 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the rrd@0.0.5 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the rrd package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls rrd
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /tmp/node_rrd/npm-debug.log
```

I changed the revision to this one :

```
/tmp/node_rrd $ git reset --hard 5b73f3e5f76613f55eafb0008c094915e87e7b6d
HEAD is now at 5b73f3e Merge pull request #14 from djkeeg/master
/tmp/node_rrd $ sudo npm -g install
-
> rrd@0.0.5 install /usr/local/lib/node_modules/rrd
> node-gyp rebuild

gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/0.12.6"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/local/lib/node_modules/rrd/.node-gyp"
make: Entering directory '/usr/local/lib/node_modules/rrd/build'
  CXX(target) Release/obj.target/rrd_bindings/src/node_rrd_create.o
  CXX(target) Release/obj.target/rrd_bindings/src/node_rrd_update.o
  CXX(target) Release/obj.target/rrd_bindings/src/node_rrd_fetch.o
  CXX(target) Release/obj.target/rrd_bindings/src/node_rrd_last.o
  CXX(target) Release/obj.target/rrd_bindings/src/node_rrd_info.o
  CXX(target) Release/obj.target/rrd_bindings/src/node_rrd.o
  SOLINK_MODULE(target) Release/obj.target/rrd_bindings.node
  COPY Release/rrd_bindings.node
make: Leaving directory '/usr/local/lib/node_modules/rrd/build'
 rrd@0.0.5 /usr/local/lib/node_modules/rrd
├── bindings@1.2.1
├── arguee@0.0.2
└── nan@1.8.4
```

**Comment by tdjordan** [comment]
@wiseflat, what version of gcc do you have?

What does gcc --version say?
